services:
  postgres:
    image: postgres:15
    container_name: appliedAi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres-data:/var/lib/postgresql/data

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile.dev
    volumes:
      - ./services/payment-service/src:/app/services/payment-service/src
    ports:
      - "3001:3001"
    command: pnpm start:dev
    depends_on:
      - postgres

  subscription-service:
    build:
      context: .
      dockerfile: services/subscription-service/Dockerfile.dev
    volumes:
      - ./services/subscription-service/src:/app/services/subscription-service/src
    ports:
      - "3000:3000"
    command: pnpm start:dev
    depends_on:
      - postgres

